version: '3.7'

services:
  # Start docker container for PostgreSQL to mock RDS
  postgres:
    image: postgres:11.5-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: opendatacubepassword
    restart: always

  # Start docker container for datacube-wps
  wps:
    build: .
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=postgres
      - DB_PORT=5432
      - AWS_DEFAULT_REGION=ap-southeast-2
      - AWS_NO_SIGN_REQUEST=YES
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - CPL_VSIL_CURL_ALLOWED_EXTENSIONS=.tif,.tiff
      - GDAL_HTTP_MAX_RETRY=10
      - GDAL_HTTP_RETRY_DELAY=1
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/mnt/artifacts

  # start indexer container
  index:
     image: opendatacube/datacube-index:0.0.13
     environment:
        - DB_HOSTNAME=postgres
        - DB_USERNAME=postgres
        - DB_PASSWORD=opendatacubepassword
        - DB_DATABASE=postgres
        - DB_PORT=5432
        - AWS_DEFAULT_REGION=ap-southeast-2
     depends_on:
        - postgres
     entrypoint: bash -c 'sleep infinity'
